version: "2"
services:
    server:
        build: .
        container_name: vk_text_classifier_server
        command: gunicorn api:app -b 0.0.0.0:9999 -k gevent --worker-connections 1000 -t 90
        ports:
          - "9999:9999"
        links:
          - redis
        depends_on:
          - redis
    redis:
        image: "redis:latest"
        container_name: vk_text_classifier_redis
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
          - "6379:6379"
        volumes:
          - ./redis.conf:/usr/local/etc/redis/redis.conf
          - ./assets/dump.rdb:/data/dump.rdb